# Generated by Django 6.0.4 on 2026-05-08 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agro', '0005_empresa_deposito_insumos_default_and_more'),
        ('gestion_agro', '0023_facturacompra_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto aplicado')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='gestion_agro.facturacompra', verbose_name='Factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='administracion.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Aplicación de pago',
                'verbose_name_plural': 'Aplicaciones de pago',
            },
        ),
    ]
