# Generated by Django 6.0.4 on 2026-05-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto aplicado')),
            ],
            options={
                'verbose_name': 'Aplicación de cobro',
                'verbose_name_plural': 'Aplicaciones de cobro',
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfe_numero', models.CharField(max_length=20, verbose_name='NF-e número')),
                ('nfe_serie', models.CharField(default='1', max_length=5, verbose_name='Serie')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas_venta/', verbose_name='PDF')),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factura de venta',
                'verbose_name_plural': 'Facturas de venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaVentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad (kg)')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Ítem de factura de venta',
                'verbose_name_plural': 'Ítems de factura de venta',
            },
        ),
    ]
