# Generated by Django 6.0.4 on 2026-05-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_aplicacioncobro_cobro_facturaventa_facturaventaitem'),
        ('agro', '0005_empresa_deposito_insumos_default_and_more'),
        ('gestion_agro', '0024_entregadepositoexterno_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='aplicacioncobro',
            name='cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='administracion.cobro', verbose_name='Cobro'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_venta', to='gestion_agro.entregadepositoexterno', verbose_name='Entrega depósito externo'),
        ),
        migrations.AddField(
            model_name='aplicacioncobro',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='administracion.facturaventa', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='facturaventaitem',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administracion.facturaventa', verbose_name='Factura'),
        ),
        migrations.AlterUniqueTogether(
            name='facturaventa',
            unique_together={('empresa', 'cliente', 'nfe_numero')},
        ),
    ]
