# Generated by Django 6.0.5 on 2026-06-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_recibo_numero_fecha_medioCobro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionrecibo',
            options={'verbose_name': 'Aplicación de recibo', 'verbose_name_plural': 'Aplicaciones de recibo'},
        ),
        migrations.AlterUniqueTogether(
            name='facturaventa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aplicacionrecibo',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='administracion.recibo', verbose_name='Recibo'),
        ),
        migrations.AlterField(
            model_name='facturaventaitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facturaventaitem',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administracion.facturaventa'),
        ),
        migrations.AlterField(
            model_name='facturaventaitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
