# Generated by Django 6.0.4 on 2026-04-27 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agro', '0004_empresa_calculo_costo'),
        ('gestion_agro', '0020_movimientostock_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('prescripcion', 'Mapa de prescripción'), ('analisis_suelo', 'Análisis de suelo'), ('rendimiento', 'Mapa de rendimiento'), ('ndvi', 'NDVI / vegetación'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('variable', models.CharField(help_text='Nombre del campo numérico en el shapefile (ej: rate, ph, k)', max_length=50)),
                ('unidad', models.CharField(blank=True, default='', max_length=20)),
                ('geojson_file', models.FileField(upload_to='capas_geojson/')),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('valor_promedio', models.FloatField(blank=True, null=True)),
                ('num_features', models.IntegerField(default=0)),
                ('bbox_min_lng', models.FloatField(blank=True, null=True)),
                ('bbox_min_lat', models.FloatField(blank=True, null=True)),
                ('bbox_max_lng', models.FloatField(blank=True, null=True)),
                ('bbox_max_lat', models.FloatField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='gestion_agro.campo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='agro.empresa')),
            ],
            options={
                'verbose_name': 'Capa de análisis',
                'verbose_name_plural': 'Capas de análisis',
                'ordering': ['-creado'],
            },
        ),
    ]
