# Generated by Django 6.0.4 on 2026-05-08 13:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0025_campo_boundary_geojson'),
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVICaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_imagen', models.DateField(verbose_name='Fecha imagen satélite')),
                ('fecha_proceso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha proceso')),
                ('origen', models.CharField(choices=[('AUTO', 'Sentinel-2 automático'), ('MANUAL', 'Subida manual')], default='AUTO', max_length=10)),
                ('ndvi_promedio', models.FloatField(blank=True, null=True, verbose_name='NDVI promedio')),
                ('ndvi_min', models.FloatField(blank=True, null=True, verbose_name='NDVI mínimo')),
                ('ndvi_max', models.FloatField(blank=True, null=True, verbose_name='NDVI máximo')),
                ('nubosidad_pct', models.FloatField(default=0, verbose_name='% Nubosidad')),
                ('imagen_png', models.ImageField(blank=True, null=True, upload_to='ndvi/imagenes/', verbose_name='Imagen PNG')),
                ('geojson_file', models.FileField(blank=True, null=True, upload_to='ndvi/geojson/', verbose_name='GeoJSON')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_capturas', to='gestion_agro.campo', verbose_name='Campo')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ndvi_capturas', to='gestion_agro.cicloagricola', verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Captura NDVI',
                'verbose_name_plural': 'Capturas NDVI',
                'ordering': ['-fecha_imagen'],
                'unique_together': {('campo', 'fecha_imagen')},
            },
        ),
    ]
