# Generated by Django 6.0.5 on 2026-05-15 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0036_contorno_y_modelos_analisis'),
        ('mapas', '0002_ndvicaptura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('unidad', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('tipo', models.CharField(choices=[('satelite', 'Satélite'), ('suelo', 'Análisis de suelo'), ('cosecha', 'Rendimiento / Cosecha'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('rango_minimo', models.FloatField(blank=True, null=True, verbose_name='Rango mínimo esperado')),
                ('rango_maximo', models.FloatField(blank=True, null=True, verbose_name='Rango máximo esperado')),
            ],
            options={
                'verbose_name': 'Variable analítica',
                'verbose_name_plural': 'Variables analíticas',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ndvicaptura',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ndvicaptura',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='ndvicaptura',
            name='ciclo',
        ),
        migrations.CreateModel(
            name='ArchivoAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_analiticos/', verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(choices=[('shapefile', 'Shapefile (.zip)'), ('geojson', 'GeoJSON'), ('tif', 'GeoTIFF'), ('csv', 'CSV')], max_length=20, verbose_name='Tipo de archivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('area_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_analiticos', to='gestion_agro.areacampo', verbose_name='Área del campo')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_analiticos', to='gestion_agro.campo', verbose_name='Campo')),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_analiticos', to='gestion_agro.cicloagricola', verbose_name='Ciclo agrícola')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='mapas.variableanalitica', verbose_name='Variable analítica')),
            ],
            options={
                'verbose_name': 'Archivo analítico',
                'verbose_name_plural': 'Archivos analíticos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='CapaMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('datos', models.JSONField(blank=True, null=True, verbose_name='Datos GeoJSON')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('area_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_mapa', to='gestion_agro.areacampo', verbose_name='Área del campo')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas_mapa', to='gestion_agro.campo', verbose_name='Campo')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_mapa', to='gestion_agro.cicloagricola', verbose_name='Ciclo agrícola')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Capa de mapa',
                'verbose_name_plural': 'Capas de mapa',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CapturaSatelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de imagen')),
                ('fuente', models.CharField(choices=[('sentinel2', 'Sentinel-2'), ('landsat', 'Landsat'), ('manual', 'Manual')], default='sentinel2', max_length=20, verbose_name='Fuente')),
                ('nubosidad_pct', models.FloatField(default=0, verbose_name='% Nubosidad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha procesado')),
                ('area_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas_satelite', to='gestion_agro.areacampo', verbose_name='Área del campo')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas_satelite', to='gestion_agro.campo', verbose_name='Campo')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas_satelite', to='gestion_agro.cicloagricola', verbose_name='Ciclo agrícola')),
            ],
            options={
                'verbose_name': 'Captura satelital',
                'verbose_name_plural': 'Capturas satelitales',
                'ordering': ['-fecha'],
                'unique_together': {('campo', 'area_campo', 'fecha', 'fuente')},
            },
        ),
        migrations.CreateModel(
            name='EstiloCapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paleta', models.JSONField(default=list, help_text='Lista de colores hex ordenados de menor a mayor valor', verbose_name='Paleta de colores')),
                ('opacidad', models.FloatField(default=0.7, verbose_name='Opacidad')),
                ('valor_minimo', models.FloatField(blank=True, null=True, verbose_name='Valor mínimo escala')),
                ('valor_maximo', models.FloatField(blank=True, null=True, verbose_name='Valor máximo escala')),
                ('capa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estilo', to='mapas.capamapa', verbose_name='Capa')),
            ],
            options={
                'verbose_name': 'Estilo de capa',
                'verbose_name_plural': 'Estilos de capa',
            },
        ),
        migrations.CreateModel(
            name='IndiceVegetacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ndvi', 'NDVI'), ('evi', 'EVI'), ('ndre', 'NDRE'), ('savi', 'SAVI')], max_length=10, verbose_name='Tipo de índice')),
                ('promedio', models.FloatField(verbose_name='Promedio')),
                ('minimo', models.FloatField(verbose_name='Mínimo')),
                ('maximo', models.FloatField(verbose_name='Máximo')),
                ('grilla_datos', models.JSONField(blank=True, null=True, verbose_name='Grilla de datos (píxeles)')),
                ('imagen_png', models.ImageField(blank=True, null=True, upload_to='indices/imagenes/', verbose_name='Imagen PNG')),
                ('geojson_file', models.FileField(blank=True, null=True, upload_to='indices/geojson/', verbose_name='GeoJSON')),
                ('captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='mapas.capturasatelite', verbose_name='Captura')),
            ],
            options={
                'verbose_name': 'Índice de vegetación',
                'verbose_name_plural': 'Índices de vegetación',
                'unique_together': {('captura', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='capamapa',
            name='indice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='mapas.indicevegetacion', verbose_name='Índice de vegetación'),
        ),
        migrations.CreateModel(
            name='MedicionCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('promedio', models.FloatField(verbose_name='Promedio')),
                ('minimo', models.FloatField(blank=True, null=True, verbose_name='Mínimo')),
                ('maximo', models.FloatField(blank=True, null=True, verbose_name='Máximo')),
                ('area_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones', to='gestion_agro.areacampo', verbose_name='Área del campo')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='gestion_agro.campo', verbose_name='Campo')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones', to='gestion_agro.cicloagricola', verbose_name='Ciclo agrícola')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones', to='mapas.archivoanalitico', verbose_name='Archivo origen')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='mapas.variableanalitica', verbose_name='Variable')),
            ],
            options={
                'verbose_name': 'Medición de campo',
                'verbose_name_plural': 'Mediciones de campo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='capamapa',
            name='medicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='mapas.medicioncampo', verbose_name='Medición'),
        ),
        migrations.AddField(
            model_name='capamapa',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='mapas.variableanalitica', verbose_name='Variable'),
        ),
        migrations.DeleteModel(
            name='CapaAnalisis',
        ),
        migrations.DeleteModel(
            name='NDVICaptura',
        ),
    ]
