# Generated by Django 6.0.5 on 2026-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0003_contorno_y_modelos_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoanalitico',
            name='bbox',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivoanalitico',
            name='estadisticas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivoanalitico',
            name='imagen_png',
            field=models.FileField(blank=True, null=True, upload_to='archivos_analiticos/png/'),
        ),
        migrations.AddField(
            model_name='archivoanalitico',
            name='leyenda',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
