# Generated by Django 6.0.5 on 2026-06-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0004_archivoanalitico_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableanalitica',
            name='tipo',
            field=models.CharField(choices=[('satelite', 'Satélite'), ('suelo', 'Análisis de suelo'), ('cosecha', 'Rendimiento / Cosecha'), ('clima', 'Clima / Lluvia'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
