# Generated by Django 6.0.3 on 2026-04-07 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_de_precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Lista de precios',
                'verbose_name_plural': 'Listas de precios',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('corto', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipodoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('factor_a_base', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Factor a unidad base')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('O', 'Ok'), ('B', 'Baja'), ('S', 'Suspendido')], default='O', max_length=1)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lista_precio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_de_precios', to='agro.lista_de_precios')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
                ('unidad_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='agro.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cotizacion', models.DecimalField(decimal_places=3, max_digits=12)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cotizacion', models.DecimalField(decimal_places=3, max_digits=12)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.pais', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.pais', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='agro.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'unique_together': {('nombre', 'provincia')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('tipo', models.CharField(default='A', max_length=1)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('direccion2', models.CharField(default='', max_length=100)),
                ('cp', models.CharField(default='', max_length=10)),
                ('telefono', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('celular', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('documento', models.CharField(default='', max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('N', 'Ingresado'), ('A', 'Aprobado'), ('S', 'Suspendido')], default='N', max_length=1)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.ciudad', verbose_name='Ciudad')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.genero', verbose_name='Genero')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.nacionalidad', verbose_name='Nacionalidad')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.provincia', verbose_name='Provincia')),
                ('tipodoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.tipodoc', verbose_name='Tipo documento')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Factor de conversión')),
                ('um_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='agro.unidad')),
                ('um_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='agro.unidad')),
            ],
            options={
                'verbose_name': 'Conversión de unidad',
                'verbose_name_plural': 'Conversiones de unidades',
                'constraints': [models.UniqueConstraint(fields=('um_origen', 'um_destino'), name='uq_conversion_um_origen_destino')],
            },
        ),
    ]
