# Generated by Django 6.0.3 on 2026-03-16 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionum',
            options={'verbose_name': 'Conversión de unidad', 'verbose_name_plural': 'Conversiones de unidades'},
        ),
        migrations.AlterField(
            model_name='conversionum',
            name='factor',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Factor de conversión'),
        ),
        migrations.AlterField(
            model_name='conversionum',
            name='um_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='agro.unidad'),
        ),
        migrations.AlterField(
            model_name='conversionum',
            name='um_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='agro.unidad'),
        ),
        migrations.AddConstraint(
            model_name='conversionum',
            constraint=models.UniqueConstraint(fields=('um_origen', 'um_destino'), name='uq_conversion_um_origen_destino'),
        ),
    ]
