# Generated by Django 6.0.3 on 2026-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='valor_maquina',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Costo Maquina'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valor_mobra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Costo MO'),
        ),
    ]
