# Generated by Django 6.0.3 on 2026-03-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_alter_conversionum_options_alter_conversionum_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_de_precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Lista de precios',
                'verbose_name_plural': 'Listas de precios',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='unidad_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='agro.unidad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='lista_precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_de_precios', to='agro.lista_de_precios'),
        ),
    ]
