# Generated by Django 6.0.3 on 2026-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_empresa_valor_maquina_empresa_valor_mobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='valor_maquina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Costo Maquina'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valor_mobra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Costo MO'),
        ),
    ]
