# Generated by Django 6.0.4 on 2026-04-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_alter_empresa_valor_maquina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='calculo_costo',
            field=models.CharField(choices=[('F', 'FIFO'), ('L', 'LIFO'), ('P', 'PONDERADO')], default='F', max_length=1, verbose_name='Cálculo de costo'),
        ),
    ]
