# Generated by Django 6.0.4 on 2026-05-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_empresa_calculo_costo'),
        ('gestion_agro', '0021_alter_actividadinsumo_um_alter_movimientostock_um_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='deposito_insumos_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_insumos_default', to='gestion_agro.deposito'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='deposito_producto_final_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_producto_final_default', to='gestion_agro.deposito'),
        ),
    ]
