# Generated by Django 6.0.4 on 2026-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_empresa_deposito_insumos_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='pct_prima_semilla',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje adicional sobre precio de consumo para grano certificado como semilla', max_digits=5, verbose_name='% Prima semilla'),
        ),
    ]
