# Generated by Django 6.0.5 on 2026-05-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0006_empresa_pct_prima_semilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='unidad_inspeccion_semilla',
            field=models.ForeignKey(blank=True, help_text='Unidad por defecto para cantidad aprobada en inspección (ej: semillas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_inspeccion_semilla', to='agro.unidad', verbose_name='Unidad inspección semilla'),
        ),
    ]
