# Generated by Django 6.0.5 on 2026-05-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0007_unidad_inspeccion_semilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='requiere_pmg',
            field=models.BooleanField(default=False, help_text='Si es verdadero, la conversión a kg usa el PMG de la variedad en lugar de un factor fijo.', verbose_name='Requiere PMG'),
        ),
    ]
