# Generated by Django 6.0.3 on 2026-03-04 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Cultura')),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubTipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('D', 'Default'), ('C', 'Cosecha'), ('V', 'Visitoria')], max_length=1)),
                ('abre_fase', models.BooleanField()),
                ('cierra_fase', models.BooleanField()),
                ('requiere_subtipo', models.BooleanField()),
                ('adicionales', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=9, unique=True, verbose_name='Campaña')),
                ('fecha_desde', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha de finalización')),
                ('activa', models.BooleanField(default=False, verbose_name='Campaña activa')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-fecha_desde'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del campo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('superficie_ha', models.DecimalField(decimal_places=2, help_text='Superficie total del campo expresada en hectáreas', max_digits=10, verbose_name='Superficie total')),
                ('image', models.ImageField(default='default.jpg', upload_to='campos', verbose_name='Imagen')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agro.ciudad', verbose_name='Ciudad / Localidad')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='CamposCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimiento', models.DecimalField(blank=True, decimal_places=2, help_text='Rendimiento obtenido (kg/ha, qq/ha, t/ha, según estándar)', max_digits=10, null=True)),
                ('comentarios_cosecha', models.TextField(blank=True, help_text='Observaciones específicas de la cosecha', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la actividad', null=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.actividadproductiva')),
            ],
        ),
        migrations.CreateModel(
            name='CamposVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantas_m2', models.IntegerField(blank=True, null=True)),
                ('malezas', models.CharField(blank=True, max_length=255, null=True)),
                ('insectos', models.CharField(blank=True, max_length=255, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vistorias/')),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.actividadproductiva')),
            ],
        ),
        migrations.CreateModel(
            name='CicloAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('superficie_ha', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implantaciones', to='gestion_agro.campana')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='implantaciones', to='gestion_agro.campo')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='gestion_agro.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número factura')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas_compra/')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Factura de compra',
                'verbose_name_plural': 'Facturas de compra',
            },
        ),
        migrations.CreateModel(
            name='FaseAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('implantacion', 'Implantación'), ('desarrollo', 'Desarrollo'), ('reproduccion', 'Reproducción'), ('maduracion', 'Maduración'), ('cosecha', 'Cosecha')], default='desarrollo', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='gestion_agro.cicloagricola')),
            ],
            options={
                'verbose_name': 'Fase agrícola',
                'verbose_name_plural': 'Fases agrícolas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion_agro.faseagricola'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='lotes')),
                ('ha_totales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ha_productivas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.campo', verbose_name='Campo')),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre presentación')),
                ('unidad_factura', models.CharField(max_length=20, verbose_name='Unidad factura')),
                ('contenido', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Contenido')),
                ('unidad_contenido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agro.unidad', verbose_name='Unidad contenido')),
            ],
            options={
                'verbose_name': 'Presentación de producto',
                'verbose_name_plural': 'Presentaciones de producto',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_facturada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_agro.facturacompra')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.presentacionproducto')),
            ],
            options={
                'verbose_name': 'Ítem de factura',
                'verbose_name_plural': 'Ítems de factura',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255, verbose_name='Nombre comercial')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.categoriaproducto', verbose_name='Categoría')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_comerciales', to='gestion_agro.cultivo', verbose_name='Cultivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_agro', to='agro.empresa', verbose_name='Empresa')),
                ('unidad_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agro.unidad', verbose_name='Unidad base')),
                ('unidad_dosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidad_dosis', to='agro.unidad', verbose_name='Unidad base')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='presentacionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.producto', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('precio_unitario', models.DecimalField(decimal_places=6, help_text='Precio promedio aplicado al momento del consumo', max_digits=14, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='gestion_agro.actividadproductiva')),
                ('factura_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.facturacompraitem')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
            },
        ),
        migrations.AddField(
            model_name='facturacompraitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.producto'),
        ),
        migrations.CreateModel(
            name='ActividadInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosis_insumos', to='agro.unidad')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='gestion_agro.actividadproductiva')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoNormalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_descripcion', models.TextField(verbose_name='Descripción original')),
                ('origen_codigo', models.CharField(blank=True, max_length=50, verbose_name='Código original')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('envase_tipo', models.CharField(max_length=50, verbose_name='Tipo de envase')),
                ('envase_desc', models.CharField(max_length=100, verbose_name='Descripción envase')),
                ('contenido_cantidad', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad por envase')),
                ('contenido_unidad', models.CharField(max_length=10, verbose_name='Unidad contenido')),
                ('contenido_estandar', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad estándar')),
                ('unidad_estandar', models.CharField(choices=[('kg', 'Kilogramos'), ('L', 'Litros'), ('g', 'Gramos'), ('ml', 'Mililitros'), ('ha', 'Hectárea'), ('und', 'Unidad')], max_length=10, verbose_name='Unidad estándar')),
                ('dosis_recomendada', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Dosis (por ha)')),
                ('dosis_unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('L', 'Litros'), ('g', 'Gramos'), ('ml', 'Mililitros'), ('ha', 'Hectárea'), ('und', 'Unidad')], default='L', max_length=10, verbose_name='Unidad dosis')),
                ('precio_envase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por envase')),
                ('costo_por_unidad', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Costo por unidad estándar')),
                ('costo_por_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo por hectárea')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha importación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto normalizado',
                'verbose_name_plural': 'Productos normalizados',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_normalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_agro.productonormalizado', verbose_name='Producto normalizado'),
        ),
        migrations.CreateModel(
            name='Proveedor_agro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('identificador', models.CharField(blank=True, max_length=30, null=True, verbose_name='CUIT / CNPJ')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'unique_together': {('empresa', 'razon_social')},
            },
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_agro.proveedor_agro', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.producto')),
            ],
            options={
                'verbose_name': 'Stock actual',
                'verbose_name_plural': 'Stock actual',
            },
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='siembra_subtipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.subtipoactividad'),
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.tipoactividad'),
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Variedade')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='gestion_agro.cultivo', verbose_name='Cultura')),
            ],
            options={
                'verbose_name': 'Variedade',
                'verbose_name_plural': 'Variedades',
                'ordering': ['cultivo__nombre', 'nombre'],
                'unique_together': {('cultivo', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_comerciales', to='gestion_agro.variedad', verbose_name='Variedad'),
        ),
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('empresa', 'proveedor', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'nombre_comercial')},
        ),
    ]
