# Generated by Django 6.0.3 on 2026-04-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
