# Generated by Django 6.0.3 on 2026-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtipoactividad',
            name='puede_abrir_fase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='puede_cerrar_fase',
            field=models.BooleanField(default=False),
        ),
    ]
