# Generated by Django 6.0.3 on 2026-03-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='actividadproductiva',
            name='siembra_subtipo',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='abre_fase',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='adicionales',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='cierra_fase',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='requiere_insumo',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='requiere_maq',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='requiere_mo',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='requiere_subtipo',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='tipo',
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='subtipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='gestion_agro.subtipoactividad'),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='tipo_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='gestion_agro.tipoactividad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actividadproductiva',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='gestion_agro.tipoactividad'),
        ),
        migrations.AlterField(
            model_name='subtipoactividad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subtipoactividad',
            unique_together={('tipo_actividad', 'nombre')},
        ),
        migrations.CreateModel(
            name='TipoActividadCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_actividad', to='gestion_agro.caracteristicaactividad')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_asignadas', to='gestion_agro.tipoactividad')),
            ],
            options={
                'unique_together': {('tipo_actividad', 'caracteristica')},
            },
        ),
    ]
