# Generated by Django 6.0.3 on 2026-03-16 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
        ('gestion_agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSemilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Producto semilla',
                'verbose_name_plural': 'Productos semilla',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1, max_length=50, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='maneja_stock',
            field=models.BooleanField(default=True, verbose_name='Maneja stock'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=2, max_length=255, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='gestion_agro.categoriaproducto', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='agro.empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_unidad_base', to='agro.unidad', verbose_name='Unidad base'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_producto_empresa_codigo'),
        ),
        migrations.AddField(
            model_name='productosemilla',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_semilla', to='gestion_agro.cultivo', verbose_name='Cultivo'),
        ),
        migrations.AddField(
            model_name='productosemilla',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_semilla', to='gestion_agro.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productosemilla',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_semilla', to='gestion_agro.variedad', verbose_name='Variedad'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cultivo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto_normalizado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_dosis',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='variedad',
        ),
    ]
