# Generated by Django 6.0.3 on 2026-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0002_productosemilla_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='codigo',
            field=models.CharField(default=2, max_length=10, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
