# Generated by Django 6.0.3 on 2026-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0002_subtipoactividad_puede_abrir_fase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtipoactividad',
            name='puede_abrir_fase',
        ),
        migrations.RemoveField(
            model_name='subtipoactividad',
            name='puede_cerrar_fase',
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='abre_fase',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='cierra_fase',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
