# Generated by Django 6.0.3 on 2026-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0003_categoriaproducto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadinsumo',
            name='cantidad_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
