# Generated by Django 6.0.3 on 2026-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0003_remove_subtipoactividad_puede_abrir_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtipoactividad',
            name='valor_maquina',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True, verbose_name='Costo Maquina'),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='valor_mobra',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True, verbose_name='Costo MO'),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='valor_x_ha_mo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='valor_x_ha_mq',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='valor_maquina',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True, verbose_name='Costo Maquina'),
        ),
    ]
