# Generated by Django 6.0.3 on 2026-03-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0004_alter_actividadinsumo_cantidad_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividadCategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_actividad', to='gestion_agro.categoriaproducto')),
                ('subtipo_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='gestion_agro.subtipoactividad')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='gestion_agro.tipoactividad')),
            ],
            options={
                'unique_together': {('tipo_actividad', 'subtipo_actividad', 'categoria_producto')},
            },
        ),
    ]
