# Generated by Django 6.0.3 on 2026-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0004_subtipoactividad_valor_maquina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadproductiva',
            name='cantidad_h_maq',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Costo MO'),
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='cantidad_hombre',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Costo MO'),
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='valor_h_maq',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=4, null=True, verbose_name='Costo MO'),
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='valor_hombre',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=4, null=True, verbose_name='Costo MO'),
        ),
    ]
