# Generated by Django 6.0.3 on 2026-03-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_lista_de_precios_empresa_unidad_default_and_more'),
        ('gestion_agro', '0005_tipoactividadcategoriaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CP', 'Compra'), ('V', 'Venta')], max_length=2)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='agro.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_precios', to='agro.moneda')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_precios', to='agro.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=4, max_digits=18)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_agro.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='gestion_agro.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_lista', to='agro.unidad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='listaprecio',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_lista_precio_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='listapreciodetalle',
            constraint=models.UniqueConstraint(fields=('lista_precio', 'producto', 'unidad'), name='uq_lista_precio_producto_unidad'),
        ),
    ]
