# Generated by Django 6.0.3 on 2026-04-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0005_actividadproductiva_cantidad_h_maq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='valor_x_ha_mq',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
