# Generated by Django 6.0.3 on 2026-04-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0007_remove_subtipoactividad_valor_mobra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadproductiva',
            name='valor_h_maq',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='actividadproductiva',
            name='valor_hombre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subtipoactividad',
            name='valor_maquina',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Costo por hora de máquina'),
        ),
        migrations.AlterField(
            model_name='subtipoactividad',
            name='valor_x_ha_mo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas de mano de obra por ha'),
        ),
        migrations.AlterField(
            model_name='subtipoactividad',
            name='valor_x_ha_mq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas de máquina por ha'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='valor_maquina',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Costo por hora de máquina'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='valor_x_ha_mq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas de máquina por ha'),
        ),
    ]
