# Generated by Django 6.0.3 on 2026-04-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0008_alter_actividadproductiva_valor_h_maq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='valor_mo',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=18, null=True, verbose_name='Costo por hora de mano de obra'),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='valor_x_ha_mo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas de mano de obra por ha'),
        ),
    ]
