# Generated by Django 6.0.4 on 2026-04-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_alter_empresa_valor_maquina_and_more'),
        ('gestion_agro', '0009_tipoactividad_valor_mo_tipoactividad_valor_x_ha_mo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor_agro',
            new_name='Proveedor',
        ),
    ]
