# Generated by Django 6.0.4 on 2026-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0010_rename_proveedor_agro_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='gestion_agro.categoriaproducto'),
        ),
    ]
