# Generated by Django 6.0.4 on 2026-04-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0011_tipoactividad_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoactividad',
            name='categorias',
        ),
    ]
