# Generated by Django 6.0.4 on 2026-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0012_remove_tipoactividad_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadproductiva',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='total_maq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='actividadproductiva',
            name='total_mo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
