# Generated by Django 6.0.4 on 2026-04-16 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0013_actividadproductiva_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='actividad',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='actividad_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='gestion_agro.actividadinsumo'),
        ),
    ]
