# Generated by Django 6.0.4 on 2026-04-21 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0014_remove_movimientostock_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion_defualt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_presentacion_default', to='gestion_agro.presentacionproducto', verbose_name='Presentación default'),
        ),
    ]
