# Generated by Django 6.0.4 on 2026-04-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0015_producto_presentacion_defualt'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='es_semilla',
            field=models.BooleanField(default=False, verbose_name='Es semilla'),
        ),
    ]
