# Generated by Django 6.0.4 on 2026-04-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0016_categoriaproducto_es_semilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloagricola',
            name='producto_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_producto_final', to='gestion_agro.producto'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='producto_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='gestion_agro.producto', verbose_name='Producto asociado'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='productos_finales',
            field=models.ManyToManyField(blank=True, related_name='cultivos_finales', to='gestion_agro.producto', verbose_name='Productos finales (cosecha)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_final',
            field=models.BooleanField(default=False, verbose_name='Producto final (cosecha)'),
        ),
    ]
