# Generated by Django 6.0.4 on 2026-04-23 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_empresa_calculo_costo'),
        ('gestion_agro', '0017_cicloagricola_producto_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='agro.empresa'),
            preserve_default=False,
        ),
    ]
