# Generated by Django 6.0.4 on 2026-04-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0018_cultivo_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cicloagricola',
            options={'ordering': ['-fecha_inicio', '-id'], 'verbose_name': 'Ciclo agrícola', 'verbose_name_plural': 'Ciclos agrícolas'},
        ),
    ]
