# Generated by Django 6.0.4 on 2026-04-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0019_alter_cicloagricola_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='gestion_agro.actividadproductiva'),
        ),
    ]
