# Generated by Django 6.0.4 on 2026-05-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_empresa_calculo_costo'),
        ('gestion_agro', '0020_movimientostock_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadinsumo',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_insumos', to='agro.unidad'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='agro.unidad'),
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='deposito_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='gestion_agro.deposito'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='deposito_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='gestion_agro.deposito'),
        ),
        migrations.AddField(
            model_name='producto',
            name='deposito_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_default', to='gestion_agro.deposito'),
        ),
    ]
