# Generated by Django 6.0.4 on 2026-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0021_alter_actividadinsumo_um_alter_movimientostock_um_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposito',
            options={},
        ),
        migrations.AddField(
            model_name='deposito',
            name='tipo',
            field=models.CharField(choices=[('PROPIO', 'Propio'), ('EXTERNO', 'Externo')], default='PROPIO', max_length=10),
        ),
    ]
