# Generated by Django 6.0.4 on 2026-05-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0022_alter_deposito_options_deposito_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
    ]
