# Generated by Django 6.0.4 on 2026-05-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_empresa_deposito_insumos_default_and_more'),
        ('gestion_agro', '0023_facturacompra_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDepositoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSUMO', 'Consumo'), ('SEMILLA', 'Semilla')], max_length=10, verbose_name='Tipo')),
                ('nfe_numero', models.CharField(blank=True, max_length=20, verbose_name='NF-e número')),
                ('nfe_serie', models.CharField(blank=True, default='1', max_length=5, verbose_name='Serie')),
                ('ticket_balanza', models.CharField(blank=True, max_length=20, verbose_name='Ticket balanza')),
                ('peso_bruto', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso bruto (kg)')),
                ('tara', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Tara (kg)')),
                ('pct_impureza', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Impureza')),
                ('kg_impureza', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='kg Impureza')),
                ('pct_umidade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Umidade')),
                ('kg_umidade', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='kg Umidade')),
                ('graus_umidade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Graus umidade')),
                ('total_descuentos', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Total descuentos (kg)')),
                ('chave_nfe', models.CharField(blank=True, max_length=60, verbose_name='Chave NF-e')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='entregas_externas/', verbose_name='PDF')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_externas', to='gestion_agro.cicloagricola', verbose_name='Ciclo agrícola')),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_externa', to='gestion_agro.movimientostock', verbose_name='Movimiento de stock')),
            ],
            options={
                'verbose_name': 'Entrega depósito externo',
                'verbose_name_plural': 'Entregas depósito externo',
                'ordering': ['-movimiento__fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('identificador', models.CharField(blank=True, max_length=30, null=True, verbose_name='CUIT / CNPJ')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('empresa', 'razon_social')},
            },
        ),
    ]
