# Generated by Django 6.0.4 on 2026-05-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0024_entregadepositoexterno_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='boundary_geojson',
            field=models.TextField(blank=True, null=True, verbose_name='Contorno del campo (GeoJSON)'),
        ),
    ]
