# Generated by Django 6.0.5 on 2026-05-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0006_empresa_pct_prima_semilla'),
        ('gestion_agro', '0025_campo_boundary_geojson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camposcosecha',
            options={'verbose_name': 'Cosecha', 'verbose_name_plural': 'Cosechas'},
        ),
        migrations.AddField(
            model_name='actividadinsumo',
            name='densidad_siembra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Densidad de siembra (semillas/ha)'),
        ),
        migrations.AddField(
            model_name='camposcosecha',
            name='kg_consumo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Kg destinados a consumo'),
        ),
        migrations.AddField(
            model_name='camposcosecha',
            name='kg_semilla',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Kg destinados a semilla'),
        ),
        migrations.AlterField(
            model_name='camposcosecha',
            name='comentarios_cosecha',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de cosecha'),
        ),
        migrations.AlterField(
            model_name='camposcosecha',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='camposcosecha',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rendimiento obtenido (kg/ha, qq/ha, t/ha, según estándar)', max_digits=10, null=True, verbose_name='Rendimiento (por ha)'),
        ),
        migrations.CreateModel(
            name='CamposInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_semilla_mult_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cantidad aprobada (por ha)')),
                ('resultado', models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=10, null=True, verbose_name='Resultado')),
                ('responsable', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable')),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_agro.actividadproductiva')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_unidad_medida', to='agro.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Inspección de semilla',
                'verbose_name_plural': 'Inspecciones de semilla',
            },
        ),
    ]
