# Generated by Django 6.0.5 on 2026-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0026_inspeccion_semilla_cosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='requiere_inspeccion',
            field=models.BooleanField(default=False, verbose_name='Requiere inspección semilla'),
        ),
    ]
