# Generated by Django 6.0.5 on 2026-05-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0027_requiere_inspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosemilla',
            name='pmg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso de mil granos en gramos. Se usa para convertir semillas ↔ kg.', max_digits=8, null=True, verbose_name='PMG (g)'),
        ),
    ]
