# Generated by Django 6.0.5 on 2026-05-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0028_pmg_producto_semilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosemilla',
            name='pmg',
        ),
        migrations.AddField(
            model_name='variedad',
            name='pmg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso de mil granos en gramos', max_digits=8, null=True, verbose_name='PMG (g)'),
        ),
    ]
