# Generated by Django 6.0.5 on 2026-05-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0029_pmg_a_variedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del área')),
                ('boundary_geojson', models.TextField(blank=True, null=True, verbose_name='GeoJSON')),
                ('superficie_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Superficie (ha)')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='gestion_agro.campo', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'Área del campo',
                'verbose_name_plural': 'Áreas del campo',
                'ordering': ['nombre'],
            },
        ),
    ]
