# Generated by Django 6.0.5 on 2026-05-09 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0030_area_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='cosecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='gestion_agro.camposcosecha', verbose_name='Cosecha'),
        ),
    ]
