# Generated by Django 6.0.5 on 2026-05-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0031_movimientostock_cosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='es_semilla_cosecha',
            field=models.BooleanField(default=False, verbose_name='Es porción semilla de cosecha'),
        ),
    ]
