# Generated by Django 6.0.5 on 2026-05-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0035_movimientostock_factura_venta_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacampo',
            name='boundary_geojson',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='boundary_geojson',
        ),
        migrations.AddField(
            model_name='areacampo',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='gestion_agro.cicloagricola', verbose_name='Ciclo agrícola'),
        ),
        migrations.AddField(
            model_name='areacampo',
            name='contorno',
            field=models.TextField(blank=True, null=True, verbose_name='Contorno (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='campo',
            name='contorno',
            field=models.TextField(blank=True, null=True, verbose_name='Contorno (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='cicloagricola',
            name='contorno',
            field=models.TextField(blank=True, null=True, verbose_name='Contorno del lote (GeoJSON)'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('VENTA', 'Venta')], max_length=10),
        ),
        migrations.DeleteModel(
            name='EntregaDepositoExterno',
        ),
    ]
