# Generated by Django 6.0.5 on 2026-05-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0036_contorno_y_modelos_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloagricola',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='gestion_agro.areacampo'),
        ),
    ]
