# Generated by Django 5.2 on 2026-06-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0039_unificar_destino_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variedad',
            options={'ordering': ['cultivo__nombre', 'nombre'], 'verbose_name': 'Variedad', 'verbose_name_plural': 'Variedades'},
        ),
        migrations.AlterField(
            model_name='variedad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Variedad'),
        ),
        migrations.DeleteModel(
            name='ListaPrecioDetalle',
        ),
        migrations.DeleteModel(
            name='ListaPrecio',
        ),
    ]
