# Generated by Django 5.2 on 2026-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0040_limpieza_revision_gestion_agro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='superficie_ha',
            field=models.DecimalField(decimal_places=2, help_text='Superficie productiva del campo expresada en hectáreas', max_digits=10, verbose_name='Superficie productiva (ha)'),
        ),
    ]
