# Generated by Django 5.2 on 2026-06-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0041_alter_campo_superficie_ha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descripción'),
        ),
    ]
