# Generated by Django 6.0.5 on 2026-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agro', '0044_tipo_inspeccion_subtipo_limpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='nombre_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='nombre_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subtipoactividad',
            name='nombre_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='nombre_es',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='nombre_pt',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
